user_interests = [
    "Artificial Intelligence",
    "Machine Learning",
    "Data Science",
    "Natural Language Processing",
    "Computer Vision",
    "Big Data",
    "Internet of Things",
    "Blockchain",
    "Cybersecurity",
    "Cloud Computing",
    "Software Engineering",
    "Web Development",
    "Mobile Development",
    "Virtual Reality",
    "Augmented Reality",
    "Game Development",
    "Robotics",
    "3D Printing",
    "Quantum Computing",
    "Cryptocurrency",
    "FinTech",
    "Bioinformatics",
    "Environmental Science",
    "Renewable Energy",
    "Electric Vehicles",
    "Sustainable Development",
    "Entrepreneurship",
    "Marketing",
    "Social Media",
    "Content Creation",
    "Graphic Design",
    "UI/UX Design",
    "Product Management",
    "Project Management",
    "Agile Methodology",
    "Lean Startup",
    "Investing",
    "Personal Finance",
    "Fitness",
    "Yoga",
    "Meditation",
    "Cooking",
    "Baking",
    "Wine Tasting",
    "Travel",
    "Photography",
    "Reading",
    "Writing",
    "Music",
    "Film",
    "Theatre",
    "Fine Arts",
    "Fashion",
    "Beauty",
    "Gaming",
    "Sports",
    "Outdoor Activities",
    "Hiking",
    "Camping",
    "Fishing",
    "Skiing",
    "Snowboarding",
    "Surfing",
    "Swimming",
    "Dancing",
    "Singing",
    "Playing an Instrument",
    "Board Games",
    "Card Games",
    "Puzzles",
    "Trivia",
    "Astrology",
    "Mythology",
    "Philosophy",
    "Psychology",
    "History",
    "Geography",
    "Languages",
    "Literature",
    "Science Fiction",
    "Fantasy",
    "Mystery",
    "Thriller",
    "Horror",
    "Romance",
    "Comedy",
    "Drama",
    "Action",
    "Adventure",
    "Animation",
    "Anime",
    "Manga",
    "Cartoons",
    "Comic Books",
    "Graphic Novels",
    "Classic Literature",
    "Poetry",
    "Religion",
    "Spirituality",
    "Politics",
    "Economics",
    "Law",
    "Education",
    "Healthcare",
    "Medicine",
    "Veterinary Science",
    "Psychiatry",
    "Dentistry",
    "Nursing",
    "Engineering",
    "Architecture",
    "Construction",
    "Mechanical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Marine Engineering",
    "Materials Science",
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics"
]
